"""
Report generator using nbformat and nbconvert
"""
import os
import logging
from pathlib import Path
from typing import Dict, Any
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from nbconvert import HTMLExporter
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_report(task_id: str, metadata: Dict[str, Any]) -> str:
    """
    Generate HTML report from task execution results
    
    Args:
        task_id: Task identifier
        metadata: Task metadata dictionary
    
    Returns:
        Path to generated HTML report
    """
    from app.utils import get_data_dirs
    
    dirs = get_data_dirs()
    task_dir = dirs["tasks"] / task_id
    output_dir = task_dir / "outputs"
    
    # Create notebook
    nb = new_notebook()
    
    # Title cell
    title = f"# Data Analysis Report\n\n**Task ID:** {task_id}"
    nb.cells.append(new_markdown_cell(title))
    
    # Question cell
    question_md = f"""## Question
    
{metadata.get('question', 'N/A')}

**Dataset:** {metadata.get('dataset_id', 'N/A')}  
**Created:** {metadata.get('created_at', 'N/A')}  
**Status:** {metadata.get('status', 'N/A')}
"""
    nb.cells.append(new_markdown_cell(question_md))
    
    # Generated code cell
    code_header = new_markdown_cell("## Generated Code")
    nb.cells.append(code_header)
    
    generated_code = metadata.get('generated_code', '# No code generated')
    nb.cells.append(new_code_cell(generated_code))
    
    # Execution results
    if metadata.get('status') == 'completed':
        results_md = "## Execution Results\n\n"
        
        stdout = metadata.get('stdout', '')
        if stdout:
            results_md += f"**Output:**\n```\n{stdout}\n```\n\n"
        
        stderr = metadata.get('stderr', '')
        if stderr:
            results_md += f"**Warnings/Errors:**\n```\n{stderr}\n```\n\n"
        
        # List output files
        result_files = metadata.get('result_files', [])
        if result_files:
            results_md += "**Generated Files:**\n"
            for file in result_files:
                results_md += f"- {file}\n"
            results_md += "\n"
        
        nb.cells.append(new_markdown_cell(results_md))
        
        # Display result CSV if exists
        if 'result.csv' in result_files:
            result_csv_path = output_dir / 'result.csv'
            try:
                import pandas as pd
                df_result = pd.read_csv(result_csv_path, nrows=20)  # First 20 rows
                
                nb.cells.append(new_markdown_cell("### Result Data (first 20 rows)"))
                
                # Convert dataframe to markdown table
                result_code = f"""import pandas as pd
result_df = pd.read_csv(r'{result_csv_path}', nrows=20)
result_df"""
                nb.cells.append(new_code_cell(result_code))
                
            except Exception as e:
                logger.error(f"Failed to read result CSV: {e}")
        
        # Embed visualizations
        plot_files = [f for f in result_files if f.endswith('.png')]
        if plot_files:
            nb.cells.append(new_markdown_cell("### Visualizations"))
            
            for plot_file in plot_files:
                plot_path = output_dir / plot_file
                if plot_path.exists():
                    # Embed as markdown image with base64
                    import base64
                    with open(plot_path, 'rb') as img_file:
                        img_data = base64.b64encode(img_file.read()).decode()
                    
                    img_md = f'![{plot_file}](data:image/png;base64,{img_data})'
                    nb.cells.append(new_markdown_cell(img_md))
    
    elif metadata.get('status') == 'failed':
        error_md = f"""## Execution Failed

**Error Message:**
```
{metadata.get('error_message', 'Unknown error')}
```

**Stderr:**
```
{metadata.get('stderr', '')}
```
"""
        nb.cells.append(new_markdown_cell(error_md))
    
    # Summary cell
    summary_md = f"""---

## Summary

- **Task ID:** {task_id}
- **Status:** {metadata.get('status', 'unknown').upper()}
- **Completed:** {metadata.get('completed_at', 'N/A')}
- **Output Files:** {len(metadata.get('result_files', []))}

*Generated by Autonomous Data Analyst Agent*
"""
    nb.cells.append(new_markdown_cell(summary_md))
    
    # Save notebook
    notebook_path = task_dir / f"{task_id}.ipynb"
    with open(notebook_path, 'w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    
    logger.info(f"Notebook saved: {notebook_path}")
    
    # Convert to HTML
    html_exporter = HTMLExporter()
    html_exporter.template_name = 'classic'
    
    try:
        (body, resources) = html_exporter.from_notebook_node(nb)
        
        html_path = task_dir / f"{task_id}.html"
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(body)
        
        logger.info(f"HTML report generated: {html_path}")
        return str(html_path)
    
    except Exception as e:
        logger.error(f"Failed to convert notebook to HTML: {e}")
        # Return notebook path as fallback
        return str(notebook_path)


def generate_simple_html_report(task_id: str, metadata: Dict[str, Any]) -> str:
    """
    Generate simple HTML report (fallback if nbconvert fails)
    
    Args:
        task_id: Task identifier
        metadata: Task metadata
    
    Returns:
        Path to HTML report
    """
    from app.utils import get_data_dirs
    
    dirs = get_data_dirs()
    task_dir = dirs["tasks"] / task_id
    output_dir = task_dir / "outputs"
    
    # Build HTML content
    html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Analysis Report - {task_id}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #333; }}
        h2 {{ color: #555; border-bottom: 2px solid #007bff; padding-bottom: 10px; }}
        .info {{ background-color: #e7f3ff; padding: 15px; border-radius: 4px; margin: 15px 0; }}
        .code {{ background-color: #f4f4f4; padding: 15px; border-radius: 4px; overflow-x: auto; }}
        pre {{ margin: 0; white-space: pre-wrap; }}
        .success {{ color: #28a745; }}
        .error {{ color: #dc3545; }}
        img {{ max-width: 100%; height: auto; margin: 20px 0; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Data Analysis Report</h1>
        
        <div class="info">
            <strong>Task ID:</strong> {task_id}<br>
            <strong>Status:</strong> <span class="{'success' if metadata.get('status') == 'completed' else 'error'}">{metadata.get('status', 'unknown').upper()}</span><br>
            <strong>Created:</strong> {metadata.get('created_at', 'N/A')}<br>
            <strong>Completed:</strong> {metadata.get('completed_at', 'N/A')}
        </div>
        
        <h2>Question</h2>
        <p>{metadata.get('question', 'N/A')}</p>
        
        <h2>Generated Code</h2>
        <div class="code">
            <pre><code>{metadata.get('generated_code', '# No code generated')}</code></pre>
        </div>
"""
    
    if metadata.get('status') == 'completed':
        html_content += f"""
        <h2>Execution Results</h2>
        
        <h3>Output</h3>
        <div class="code">
            <pre>{metadata.get('stdout', 'No output')}</pre>
        </div>
"""
        
        if metadata.get('stderr'):
            html_content += f"""
        <h3>Warnings/Errors</h3>
        <div class="code">
            <pre>{metadata.get('stderr', '')}</pre>
        </div>
"""
        
        # Include images
        result_files = metadata.get('result_files', [])
        plot_files = [f for f in result_files if f.endswith('.png')]
        
        if plot_files:
            html_content += "<h2>Visualizations</h2>"
            for plot_file in plot_files:
                plot_path = output_dir / plot_file
                if plot_path.exists():
                    import base64
                    with open(plot_path, 'rb') as img_file:
                        img_data = base64.b64encode(img_file.read()).decode()
                    html_content += f'<img src="data:image/png;base64,{img_data}" alt="{plot_file}">'
    
    elif metadata.get('status') == 'failed':
        html_content += f"""
        <h2>Execution Failed</h2>
        <div class="code error">
            <pre>{metadata.get('error_message', 'Unknown error')}</pre>
        </div>
"""
    
    html_content += """
    </div>
</body>
</html>
"""
    
    # Save HTML
    html_path = task_dir / f"{task_id}.html"
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    logger.info(f"Simple HTML report generated: {html_path}")
    return str(html_path)
