"""
Utility functions for file operations and data handling
"""
import os
import shutil
import pandas as pd
from pathlib import Path
from typing import Tuple, Dict, Any
import uuid
import json
from datetime import datetime


def get_data_dirs():
    """Get configured data directories from environment"""
    base_dir = os.getenv("DATA_DIR", "./data")
    return {
        "base": Path(base_dir),
        "uploads": Path(os.getenv("UPLOAD_DIR", f"{base_dir}/uploads")),
        "tasks": Path(os.getenv("TASKS_DIR", f"{base_dir}/tasks"))
    }


def ensure_dirs():
    """Ensure all required directories exist"""
    dirs = get_data_dirs()
    for dir_path in dirs.values():
        dir_path.mkdir(parents=True, exist_ok=True)


def save_uploaded_file(file_content: bytes, filename: str) -> Tuple[str, str]:
    """
    Save uploaded CSV file and return dataset_id and path
    
    Args:
        file_content: Raw file bytes
        filename: Original filename
    
    Returns:
        Tuple of (dataset_id, file_path)
    """
    ensure_dirs()
    dirs = get_data_dirs()
    
    # Generate unique dataset ID
    dataset_id = f"ds_{uuid.uuid4().hex[:12]}"
    
    # Create dataset directory
    dataset_dir = dirs["uploads"] / dataset_id
    dataset_dir.mkdir(parents=True, exist_ok=True)
    
    # Save file
    file_path = dataset_dir / filename
    with open(file_path, "wb") as f:
        f.write(file_content)
    
    return dataset_id, str(file_path)


def get_dataset_path(dataset_id: str, prefer_processed: bool = True) -> str:
    """
    Get path to dataset CSV file
    
    Args:
        dataset_id: Dataset identifier
        prefer_processed: If True, use preprocessed version if available
    
    Returns:
        Full path to CSV file
    
    Raises:
        FileNotFoundError: If dataset doesn't exist
    """
    dirs = get_data_dirs()
    dataset_dir = dirs["uploads"] / dataset_id
    
    if not dataset_dir.exists():
        raise FileNotFoundError(f"Dataset {dataset_id} not found")
    
    # Prefer preprocessed version if it exists and requested
    if prefer_processed:
        processed_files = list(dataset_dir.glob("processed_*.csv"))
        if processed_files:
            return str(processed_files[0])
    
    # Find the original CSV file in the directory
    csv_files = [f for f in dataset_dir.glob("*.csv") if not f.name.startswith("processed_")]
    if not csv_files:
        raise FileNotFoundError(f"No CSV file found for dataset {dataset_id}")
    
    return str(csv_files[0])


def inspect_csv(file_path: str) -> Dict[str, Any]:
    """
    Inspect CSV file and return metadata
    
    Args:
        file_path: Path to CSV file
    
    Returns:
        Dictionary with rows, columns, dtypes info
    """
    df = pd.read_csv(file_path, nrows=1000)  # Sample first 1000 rows for inspection
    
    return {
        "rows": len(df),
        "columns": df.columns.tolist(),
        "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
        "sample": df.head(5).to_dict(orient="records")
    }


def create_task_dir(task_id: str) -> Path:
    """
    Create directory for task execution artifacts
    
    Args:
        task_id: Task identifier
    
    Returns:
        Path to task directory
    """
    dirs = get_data_dirs()
    task_dir = dirs["tasks"] / task_id
    task_dir.mkdir(parents=True, exist_ok=True)
    
    # Create subdirectories
    (task_dir / "outputs").mkdir(exist_ok=True)
    (task_dir / "logs").mkdir(exist_ok=True)
    
    return task_dir


def save_task_metadata(task_id: str, metadata: Dict[str, Any]):
    """Save task metadata as JSON"""
    task_dir = create_task_dir(task_id)
    metadata_path = task_dir / "metadata.json"
    
    # Convert datetime objects to ISO format strings
    def serialize(obj):
        if isinstance(obj, datetime):
            return obj.isoformat()
        raise TypeError(f"Type {type(obj)} not serializable")
    
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2, default=serialize)


def load_task_metadata(task_id: str) -> Dict[str, Any]:
    """Load task metadata from JSON"""
    dirs = get_data_dirs()
    metadata_path = dirs["tasks"] / task_id / "metadata.json"
    
    if not metadata_path.exists():
        raise FileNotFoundError(f"Task {task_id} not found")
    
    with open(metadata_path, "r") as f:
        return json.load(f)


def update_task_status(task_id: str, updates: Dict[str, Any]):
    """Update specific fields in task metadata"""
    metadata = load_task_metadata(task_id)
    metadata.update(updates)
    save_task_metadata(task_id, metadata)


def get_task_output_files(task_id: str) -> list:
    """Get list of output files generated by task"""
    dirs = get_data_dirs()
    output_dir = dirs["tasks"] / task_id / "outputs"
    
    if not output_dir.exists():
        return []
    
    return [f.name for f in output_dir.iterdir() if f.is_file()]
